# Generated by Django 5.2.8 on 2025-11-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('occupancy_status', models.CharField(default='EMPTY', max_length=10)),
                ('guest_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_on', models.BooleanField(default=False)),
                ('current_temp', models.FloatField(default=28.0)),
                ('target_temp', models.FloatField(default=25.0)),
                ('fan_speed', models.CharField(default='MID', max_length=10)),
                ('mode', models.CharField(default='COOL', max_length=10)),
                ('fee', models.FloatField(default=0.0)),
                ('total_fee', models.FloatField(default=0.0)),
                ('status', models.CharField(default='IDLE', max_length=10)),
                ('service_time', models.FloatField(default=0.0)),
                ('wait_time', models.FloatField(default=0.0)),
                ('wait_timeout', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=50)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('ac_fee', models.FloatField(default=0.0)),
                ('accommodation_fee', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
    ]
