# Generated by Django 5.2 on 2025-11-28 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="daily_rate",
            field=models.FloatField(default=300.0),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard Room"), ("KING", "King Size Room")],
                default="STANDARD",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="check_out_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ACSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("mode", models.CharField(default="COOL", max_length=10)),
                ("fan_speed", models.CharField(default="MID", max_length=10)),
                ("start_temp", models.FloatField(default=28.0)),
                ("target_temp", models.FloatField(default=25.0)),
                ("fee", models.FloatField(default=0.0)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bill",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.room"
                    ),
                ),
            ],
        ),
    ]
