# Generated by Django 5.2 on 2025-11-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_room_check_in_time_room_daily_rate_room_room_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acsession",
            name="initial_fee",
            field=models.FloatField(default=0.0),
        ),
    ]
