# Generated by Django 5.2 on 2025-12-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_acsession_initial_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="password",
            field=models.CharField(default="88888888", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
