sequenceDiagram
    participant API as System
    participant AccBill as 住宿费账单
    participant Room as 客房
    participant Reception as 前台

    API->>AccBill: calculate_Accommodation_Fee(days, fee_per_day)
    Note right of AccBill: 计算住宿总费用\n创建住宿费账单对象
    AccBill-->>API: Return(Total_Fee_of_Accommodation)
    API->>AccBill: Create_Accommodation_Bill(Room_Id, date)
    Note right of AccBill: 设置账单其他属性\n保存账单
    AccBill-->>API: Return(isOK)
    API-->>Reception: Return(isOK)
